language: python
sudo: false
matrix:
  include:
    - python: "2.7"
      env: PLONE_VERSION=4.3.x
    - python: "2.7"
      env: PLONE_VERSION=5.1.x
    - python: "2.7"
      env: PLONE_VERSION=5.2.x
    - python: "3.7"
      env: PLONE_VERSION=5.2.x
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
  - pip install -r requirements.txt
  - cp test-$PLONE_VERSION.cfg buildout.cfg
install:
  - buildout -N -t 3 annotate
  - buildout -N -t 3
script:
  - bin/test --all
after_script:
  - bin/createcoverage --output-dir=parts/test/coverage
after_success:
  - pip install -q coveralls
  - coveralls
